nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.0.cjs

enableScripts: false

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - darwin
    - linux
    - win32
