name: Release

description: Release packages

inputs:
  github_token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Version
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: pnpm nx affected --base=last-release --target=version

    - name: Tag last-release
      shell: bash
      run: git tag -f last-release

    - name: Push changes
      uses: ad-m/github-push-action@v1
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
        force: true
        tags: true
