#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs pnpm exec nx format --files

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
